---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.7.3'

inputs:
- name: ci-source
- name: server-source
  path: go/src/github.com/shumkovdenis/exapp

outputs:
- name: dist

run:
  path: sh
  args:
  - -exc
  - |
    export GOPATH=$(pwd)/go
    export PATH=$PATH:$GOPATH/bin
    dist=$(pwd)/dist
    go get -u github.com/Masterminds/glide
    cd $(pwd)/go/src/github.com/shumkovdenis/exapp
    glide install
    echo $dist
    go build -o $dist/exapp
