---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.7.3'

inputs:
- name: ci-source
- name: server-source

outputs:
- name: dist

run:
  path: sh
  args:
  - -exc
  - |
    env
    pwd
    ls -al $PWD
    go get -u github.com/Masterminds/glide
    export GOPATH=$PWD/server-source
    cd $PWD/server-source
    glide install
    go build -o $PWD/dist
