---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.7.3-alpine'

inputs:
- name: ci-source
- name: server-source

outputs:
- name: dist

run:
  path: sh
  args:
  - -exc
  - |
  set -e -u -x
  echo "Start"
  curl https://glide.sh/get | sh
  echo "Curl"
  export GOPATH=$PWD/server-source
  echo "GOPATH"
  cd $PWD/server-source
  echo "cd"
  glide install
  echo "glide"
  go build -o ./dist/exapp
