---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.7.3-alpine'

inputs:
- name: ci-source
- name: server-source

outputs:
- name: dist

run:
  path: sh
  args:
  - -exc
  - |
  set -e
  echo "Start"
