---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.7.3'

inputs:
- name: ci-source
- name: server-source
  path: /go/src/github.com/shumkovdenis/exapp

outputs:
- name: dist

run:
  path: sh
  args:
  - -exc
  - |
    env
    pwd
    ls -al $(pwd)
    ls -al /
    ls -al /go
    ls -al /go/src
    # export GOPATH=$PWD/go
    # export PATH=$PATH:$GOPATH/bin
    # go get -u github.com/Masterminds/glide
    # cd $PWD/go/src/github.com/shumkovdenis/exapp
    # glide install
    # go build -o $PWD/dist
