---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.7.3'

inputs:
- name: ci-source
- name: server-source
  path: go/src/github.com/shumkovdenis/exapp

outputs:
- name: dist

run:
  path: ci-source/scripts/build.sh
